routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ProjectControllerR;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

App::setLocale('es');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//DB::listen(function ($auery){
//    var_dump($auery->sql);
//});
Route::get('/',function (){
    return view('home');
})->name('home');


Route::view('/about','about')->name('about');
Route::resource('projects',ProjectControllerR::class);
Route::resource('contacts',ContactController::class);
Route::resource('categories',CategoryController::class);
Route::resource('departments',DepartmentController::class);
Route::resource('notifications',NotificationController::class);
Route::resource('tasks',TaskController::class);

resources/views/partials/nav.blade.php
<nav class="navbar navbar-light navbar-expand-lg bg-white shadow-sm">
    <div class="container">
        <button class="navbar-toggler" type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                data-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="{{__('Toggle navigation')}}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link {{request()->routeIs('home')?'active':''}}" href="{{ route('home') }}">Home</a></li>
                <li class="nav-item"><a class="nav-link {{request()->routeIs('contacts.*')?'active':''}}" href="{{ route('contacts.index') }}">Contact</a></li>
                <li class="nav-item"><a class="nav-link {{request()->routeIs('departments.*')?'active':''}} " href="{{ route('departments.index') }}">Departamentos</a></li>
                <li class="nav-item"><a class="nav-link {{request()->routeIs('about')?'active':''}} " href="{{ route('about') }}">About</a></li>
                <li class="nav-item"><a class="nav-link {{request()->routeIs('projects.*')?'active':''}} " href="{{ route('projects.index') }}">Projects</a></li>
                <li class="nav-item"><a class="nav-link {{request()->routeIs('categories.*')?'active':''}} " href="{{ route('categories.index') }}">Categorias</a></li>
                <li class="nav-item"><a class="nav-link {{request()->routeIs('notifications.*')?'active':''}} " href="{{ route('notifications.index') }}">Notificaciones</a></li>
                <li class="nav-item"><a class="nav-link {{request()->routeIs('tasks.*')?'active':''}} " href="{{ route('tasks.index') }}">Tareas</a></li>
            </ul>
        </div>
    </div>

</nav>

resources/views/partials/session-status.blade.php
@if(session('status'))
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        {{session('status')}}
        <button type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif