routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ProjectControllerR;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

App::setLocale('es');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//DB::listen(function ($auery){
//    var_dump($auery->sql);
//});
Route::get('/',function (){
    return view('home');
})->name('home');


Route::view('/about','about')->name('about');
Route::resource('projects',ProjectControllerR::class);
Route::resource('contacts',ContactController::class);
Route::resource('categories',CategoryController::class);
Route::resource('departments',DepartmentController::class);
Route::resource('notifications',NotificationController::class);
Route::resource('tasks',TaskController::class);

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;

    protected $fillable=['title','description','category_id'];

    public function category(){
        return $this->belongsTo(Category::class);
//        return $this->belongsTo(Category::class,'category_id');
//        pro defecto laravel asume que la llave foranea se llama cateroy_id
    }


}

resources/views/projects/create.blade.php
@extends('layout')
@section('title','Portfolio')

@section('content')

    <div class="container">
        <a href="{{route('projects.index')}}">Proyectos</a>

        <div class="row">
            <div class="col-12 col-sm-3 col-lg-6 mx-auto">

                <form class="bg-white shadow rounded py-3" action="{{route('projects.store')}}" method="POST">
                    <h3 class="display-4">Crear Proyecto</h3>

                    @csrf
                    <div class="form-group ml-4 ">
                        <label for="">Titulo del proyecto
                            <input class="form-control bg-light shadow-sm  @error('title') is-invalid @else border-0   @enderror" type="text" name="title" value="{{old('title')}}"
                                   placeholder="Nombre...">
                            @error('title')
                            <span class="span invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                            @enderror
                        </label>
                    </div>

                    <div class="form-group ml-4">
                        <label for="">Descripccion del proyecto
                            <textarea class="form-control bg-light shadow-sm  @error('description') is-invalid @else border-0  @enderror" placeholder="Descipccion del proyecto.."
                                      name="description">{{old('description')}}</textarea>
                            @error('description')
                            <span class="span invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                            @enderror
                        </label>
                    </div>

                    <div class="form-group ml-4 ">
                        <label for="category_id">Categoria del proyecto
                            <select class="form-control bg-light shadow-sm  @error('category_id') is-invalid @else border-0  @enderror" name="category_id" id="category_id">
                                <option value="">--Selecione--</option>

                                @foreach($categories as $index => $category)
                                    <option value="{{$index}}" {{old('category_id')==$index?'selected':''}}>{{$category}}</option>
                                @endforeach
                                {{--                                <option value="1">Categoria 1</option>--}}
                                {{--                                <option value="2">Categoria 2</option>--}}
                                {{--                                <option value="3">Categoria 3</option>--}}
                            </select>

                            @error('category_id')
                            <span class="span invalid-feedback" role="alert">
                                     <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </label>
                    </div>
                    <button class="btn btn-success btn-md btn-block text-center">Guardar</button>
                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/projects/edit.blade.php
@extends('layout')
@section('title','Portfolio')

@section('content')
{{--    @include('partials.session-status')--}}
<a href="{{route('projects.index')}}">Proyectos</a>

    <h1>Editar  Proyecto: {{$project->title}}</h1>
    <br>

    <form action="{{route('projects.update', $project)}}" method="POST">
        @method('PUT')
        @csrf
        <label for="">Titulo del proyecto
            <br>
            <input type="text" name="title" value="{{old('title', $project->title)}}">
            <br>
            {!!  $errors->first('title','<small>:message</small><br>') !!}
        </label>
        <br>
        <label for="">Descripccion del proyecto
            <br>
            <textarea name="description">{{old('description')!=null ? old('description'):$project->description }}</textarea>
            <br>
            {!!  $errors->first('description','<small>:message</small><br>') !!}
        </label>
        <br>
        <div class="form-group ml-4 ">
            <label for="category_id">Categoria del proyecto
                <select class="form-control bg-light shadow-sm  @error('category_id') is-invalid @else border-0  @enderror" name="category_id" id="category_id">
                    <option value="">--Selecione--</option>

                    @foreach($categories as $index => $category)
                        <option value="{{$index}}" @if($project->category_id==$index) selected   @endif>{{$category}}</option>
                    @endforeach
                    {{--                                <option value="1">Categoria 1</option>--}}
                    {{--                                <option value="2">Categoria 2</option>--}}
                    {{--                                <option value="3">Categoria 3</option>--}}
                </select>

                @error('category_id')
                <span class="span invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </label>
        </div>
        <button>Actualizar</button>
    </form>
@endsection

resources/views/projects/index.blade.php
@extends('layout')
@section('title','Portfolio')

@section('content')

    <div class="container">

        <h1>Proyectos</h1>
        <a class="btn btn-primary" href="{{route('projects.create')}}">Crear Proyecto</a>

        {{--        <select name="" id="">--}}
        {{--            @foreach($categories as $index => $category)--}}
        {{--                <option value="{{$index}}">{{$category}}</option>--}}
        {{--            @endforeach--}}
        {{--        </select>--}}


        @if(count($projects)>0)
            <div class="mt-3">
                <table class="table table-dark table-striped">
                    <thead>
                    <tr>
                        <th>Titulo</th>
                        <th>Categoria</th>
                        <th>Descripccion</th>
                        <th>Costo</th>
                        <th class="w-25">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($projects as $project)
                        <tr>
                            <td class="mr-2">{{$project->title}}</td>
                            <td>
                                @if($project->category_id)
                                    <a href="{{route('categories.show',$project->category )}}">{{$project->category->name}}</a>
                                @endif
                            </td>
                            <td>{{$project->description}}</td>
                            <td>{{$project->cost}}</td>
                            <td class="w-25">
                                <div>
                                    <a class="btn btn-light" href="{{route('projects.show', $project)}}">Ver</a>
                                    <a class="btn btn-primary" href="{{route('projects.edit', $project)}}">Editar</a>
                                    <form action="{{route('projects.destroy', $project)}}" method="POST" style="display: inline-block">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger d-flex">Eliminar</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <span>No existen proyectos</span>
                    @endforelse

                    </tbody>
                </table>
            </div>
        @endif

    </div>


@endsection

resources/views/projects/show.blade.php
@extends('layout')
@section('title',$project->title)

@section('content')
    {{--    @include('partials.session-status')--}}
    <div class="container">
        <div class="card p-5">
            <a href="{{route('projects.index')}}">Proyectos</a>

            <h2 class="display-4">Titulo del proyecto : <small>{{$project->title}}</small></h2>
            @if($project->category_id)
            <small>
                <a href="{{route('categories.show',$project->category )}}">{{$project->category->name ?? ''}}</a>
            </small>
            @else
                <strong>Sin Categoria</strong>
            @endif
            <p class="text-secondary">{{$project->description}}</p>
            <p class="text-black-50">Actualizado hace: {{$project->updated_at->diffForHumans()}}</p>
            <div class="d-flex justify-content-between align-items-center">
                <a class="btn btn-info" href="{{route('projects.edit', $project)}}">Editar</a>
                <form class="" action="{{route('projects.destroy', $project)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger">Eliminar</button>
                </form>
            </div>
        </div>
    </div>

@endsection