routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ProjectControllerR;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

App::setLocale('es');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//DB::listen(function ($auery){
//    var_dump($auery->sql);
//});
Route::get('/',function (){
    return view('home');
})->name('home');


Route::view('/about','about')->name('about');
Route::resource('projects',ProjectControllerR::class);
Route::resource('contacts',ContactController::class);
Route::resource('categories',CategoryController::class);
Route::resource('departments',DepartmentController::class);
Route::resource('notifications',NotificationController::class);
Route::resource('tasks',TaskController::class);

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

    protected $fillable=['name','description'];

    public function contacts(){
        return $this->hasMany(Contact::class);
    }

}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use App\Models\Department;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {

//        Department::factory()
//            ->has(Contact::factory()->count(3))
//            ->create();

//        Department::factory()->hasContacts(3)->create();
//        Department::factory()->hasContacts(3,[
//            'email'=>null
//        ])->create();




        $departments = Department::get();
        return view('departments.index', compact('departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        //3
        return view('departments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        //
        $request->validate(
            [
                'name' => ['required', 'unique:departments'],
                'description' => ['required'],
            ]
        );

        Department::create($request->all());
        return redirect()->route('departments.index')->with('status', 'Guardado exitosamente');

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
        return view('departments.show', [
            'department' => $department,
            'contacts' => $department->contacts->load('department')
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Department $department)
    {
        //
        return view('departments.edit', compact('department'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Department $department
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Department $department)
    {
        //
        $request->validate(
            [
                'name' => 'required',
                'description' => 'required'
            ]
        );
        $department->update($request->all());
        return redirect()->route('departments.show', $department)->with('status', 'Actualizado exitosamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Department $department
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Department $department)
    {
        //
        $department->delete();
        return redirect()->route('departments.index')->with('status', 'Eliminado exitosamente');

    }
}

resources/views/departments/create.blade.php
@extends('layout')
@section('title','Crear Departamento')

@section('content')

    <div class="container">
        <a href="{{route('departments.index')}}">Departamentos</a>

        <div class="row">
            <div class="col-12 col-sm-3 col-lg-6 mx-auto">

                <form class="bg-white shadow rounded py-3" action="{{route('departments.store')}}" method="POST">
                    <h3 class="display-4">Crear Departamento</h3>

                    @csrf
                    <div class="form-group ml-4 ">
                        <label for="">Nombre del departamento
                            <input class="form-control bg-light shadow-sm  @error('name') is-invalid @else border-0   @enderror" type="text" name="name" value="{{old('name')}}"
                                   placeholder="Nombre...">
                            @error('name')
                            <span class="span invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                            @enderror
                        </label>
                    </div>

                    <div class="form-group ml-4">
                        <label for="">Descripccion del departamento
                            <textarea class="form-control bg-light shadow-sm  @error('description') is-invalid @else border-0  @enderror" placeholder="Descipccion del proyecto.."
                                      name="description">{{old('description')}}</textarea>
                            @error('description')
                            <span class="span invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                            @enderror
                        </label>
                    </div>

                    <button class="btn btn-success btn-md btn-block text-center">Guardar</button>
                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/departments/edit.blade.php
@extends('layout')
@section('title','Editar departamento')

@section('content')
{{--    @include('partials.session-status')--}}
<a href="{{route('departments.index')}}">Departamentos</a>

    <h1>Editar  Proyecto: {{$department->title}}</h1>
    <br>

    <form action="{{route('departments.update', $department)}}" method="POST">
        @method('PUT')
        @csrf
        <label for="">Nombre del departamento
            <br>
            <input type="text" name="name" value="{{old('name', $department->name)}}">
            <br>
            {!!  $errors->first('name','<small>:message</small><br>') !!}
        </label>
        <br>
        <label for="">Descripccion del departamento
            <br>
            <textarea name="description">{{old('description')!=null ? old('description'):$department->description }}</textarea>
            <br>
            {!!  $errors->first('description','<small>:message</small><br>') !!}
        </label>
        <br>
        <button>Actualizar</button>
    </form>
@endsection

resources/views/departments/index.blade.php
@extends('layout')
@section('title','Departamentos')

@section('content')

    <div class="container">

        <h1>Departamentos</h1>
        <a class="btn btn-primary" href="{{route('departments.create')}}">Crear Departamento</a>

        @if(count($departments)>0)
            <div class="mt-3">
                <table class="table table-dark table-striped">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripccion</th>
                        <th class="w-25">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($departments as $department)
                        <tr>
                            <td class="mr-2">{{$department->name}}</td>

                            <td>{{$department->description}}</td>
                            <td class="w-25">
                                <div>
                                    <a class="btn btn-light" href="{{route('departments.show', $department)}}">Ver</a>
                                    <a class="btn btn-primary" href="{{route('departments.edit', $department)}}">Editar</a>
                                    <form action="{{route('departments.destroy', $department)}}" method="POST" style="display: inline-block">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger d-flex">Eliminar</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <span>No existen departamentos</span>
                    @endforelse

                    </tbody>
                </table>
            </div>
        @endif

    </div>


@endsection

resources/views/departments/show.blade.php
@extends('layout')
@section('title',$department->title)

@section('content')
    {{--    @include('partials.session-status')--}}
    <div class="container">
        <div class="card p-5">
            <a href="{{route('departments.index')}}">Departamentos</a>

            <h2 class="display-4"><small>{{$department->name}}</small></h2>
            <p class="text-secondary">{{$department->description}}</p>
            <p class="text-black-50">Actualizado hace: {{$department->updated_at->diffForHumans()}}</p>
            <div class="d-flex justify-content-between align-items-center">
                <a class="btn btn-info" href="{{route('departments.edit', $department)}}">Editar</a>
                <form class="" action="{{route('departments.destroy', $department)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger">Eliminar</button>
                </form>
            </div>
            <hr>
            <h1 class="text-center bg-light">Usuarios del departamento</h1>
            <div class="row">
                @foreach($contacts as $contact)
                    <div class="col-3">

                        <div class="card">
                            <h2 class="text-secondary">
                                <a href="{{route('contacts.show', $contact)}}"> {{$contact->name}}</a>
                            </h2>
                            <small class="text-secondary">{{$contact->email}}</small>
                        </div>

                    </div>
                @endforeach
            </div>
        </div>


    </div>

@endsection