routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ProjectControllerR;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

App::setLocale('es');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//DB::listen(function ($auery){
//    var_dump($auery->sql);
//});
Route::get('/',function (){
    return view('home');
})->name('home');


Route::view('/about','about')->name('about');
Route::resource('projects',ProjectControllerR::class);
Route::resource('contacts',ContactController::class);
Route::resource('categories',CategoryController::class);
Route::resource('departments',DepartmentController::class);
Route::resource('notifications',NotificationController::class);
Route::resource('tasks',TaskController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable=['name'];

    public function projects(){
        return $this->hasMany(Project::class);
//        return $this->hasMany(Project::class,'category_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::get();
        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('categories.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        //
        $request->validate(
            [
                'name' => ['required', 'unique:categories'],
            ]
        );

        Category::create($request->all());
        return redirect()->route('categories.index')->with('status', 'Guardado exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
        return view('categories.show', [
            'category' => $category,
            'projects' => $category->projects->load('category')
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Category $category)
    {
        //
//        $category = Category::find($category);
        $request->validate(
            [
                'name'=>'required'
            ]
        );
        $category->update($request->all());
        return redirect()->route('categories.show', $category)->with('status', 'Actualizado exitosamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Category $category)
    {
        //
        $category->delete();
        return redirect()->route('categories.index')->with('status', 'Eliminado exitosamente');

    }
}

resources/views/categories/create.blade.php
@extends('layout')
@section('title','Crear Categoria')

@section('content')

    <div class="container">
        <a href="{{route('categories.index')}}">Categorias</a>

        <div class="row">
            <div class="col-12 col-sm-3 col-lg-6 mx-auto">

                <form class="bg-white shadow rounded py-3" action="{{route('categories.store')}}" method="POST">
                    <h3 class="display-4">Crear Categoria</h3>

                    @csrf
                    <div class="form-group ml-4 ">
                        <label for="">Nombre de la categoria
                            <input class="form-control bg-light shadow-sm  @error('name') is-invalid @else border-0   @enderror" type="text" name="name" value="{{old('name')}}"
                                   placeholder="Nombre...">
                            @error('name')
                            <span class="span invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                             </span>
                            @enderror
                        </label>
                    </div>

                    <button class="btn btn-success btn-md btn-block text-center">Guardar</button>
                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/categories/edit.blade.php
@extends('layout')
@section('title','Editar categoria')

@section('content')
    {{--    @include('partials.session-status')--}}
    <a href="{{route('categories.index')}}">Categorias</a>

    <h1>Editar Categoria: {{$category->name}}</h1>
    <br>
    <form action="{{route('categories.update', $category)}}" method="POST">
        @method('PUT')
        @csrf
        <label for="">Titulo de la categoria
            <br>
            <input type="text" name="name" value="{{old('name', $category->name)}}">
            <br>
            {!!  $errors->first('name','<small>:message</small><br>') !!}
        </label>
        <br>
        <button>Actualizar</button>
    </form>
@endsection

resources/views/categories/index.blade.php
@extends('layout')
@section('title','Categorias')

@section('content')

    <div class="container">

        <h1>Categorias</h1>
        <a class="btn btn-primary" href="{{route('categories.create')}}">Crear Categoria</a>

        @if(count($categories)>0)
            <div class="mt-3">
                <table class="table table-dark table-striped">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th class="w-25">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($categories as $category)
                        <tr>
                            <td class="mr-2">{{$category->name}}</td>

                            <td class="w-25">
                                <div>
                                    <a class="btn btn-light" href="{{route('categories.show', $category)}}">Ver</a>
                                    <a class="btn btn-primary" href="{{route('categories.edit', $category)}}">Editar</a>
                                    <form action="{{route('categories.destroy', $category)}}" method="POST" style="display: inline-block">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger d-flex">Eliminar</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <span>No existen categorias</span>
                    @endforelse

                    </tbody>
                </table>
            </div>
        @endif

    </div>


@endsection

resources/views/categories/show.blade.php
@extends('layout')
@section('title',$category->name)

@section('content')
    {{--    @include('partials.session-status')--}}
    <div class="container">
        <div class="card p-5">
            <a href="{{route('categories.index')}}">Categorias</a>
            <h2 class="display-4">Nombre de la categoria : <small>{{$category->name}}</small></h2>
            <p class="text-black-50">Actualizado hace: {{$category->updated_at->diffForHumans()}}</p>
            <div class="d-flex justify-content-between align-items-center">
                <a class="btn btn-info" href="{{route('categories.edit', $category)}}">Editar</a>
                <form class="" action="{{route('categories.destroy', $category)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger">Eliminar</button>
                </form>
            </div>
            <hr>
            <div class="row">
                @foreach($projects as $project)
                    <div class="col-3">

                        <div class="card">
                            <h2 class="text-secondary">
                                <a href="{{route('projects.show', $project)}}"> {{$project->title}}</a>
                            </h2>
                            <p class="text-secondary">{{$project->description}}</p>
                        </div>

                    </div>
                @endforeach
            </div>

        </div>
    </div>

@endsection